//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string All_Text {
            get {
                return ResourceManager.GetString("All_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collision.
        /// </summary>
        public static string Collision_Text {
            get {
                return ResourceManager.GetString("Collision_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save {0}.
        /// </summary>
        public static string Editor_Save_Text {
            get {
                return ResourceManager.GetString("Editor_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save {0} as.
        /// </summary>
        public static string Editor_SaveAs_Text {
            get {
                return ResourceManager.GetString("Editor_SaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Editor - {0}.
        /// </summary>
        public static string Editor_Title_Text {
            get {
                return ResourceManager.GetString("Editor_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events.
        /// </summary>
        public static string EventArea_Text {
            get {
                return ResourceManager.GetString("EventArea_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string EventAreaScript_Collections_Category {
            get {
                return ResourceManager.GetString("EventAreaScript_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Area Id.
        /// </summary>
        public static string EventAreaScript_Id_Text {
            get {
                return ResourceManager.GetString("EventAreaScript_Id_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string EventAreaScript_Information_Category {
            get {
                return ResourceManager.GetString("EventAreaScript_Information_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event : {0}.
        /// </summary>
        public static string EventAreaScript_Name_Text {
            get {
                return ResourceManager.GetString("EventAreaScript_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygons.
        /// </summary>
        public static string EventAreaScript_Polygons_Text {
            get {
                return ResourceManager.GetString("EventAreaScript_Polygons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function.
        /// </summary>
        public static string Function_FunctionString_Text {
            get {
                return ResourceManager.GetString("Function_FunctionString_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function : {0}.
        /// </summary>
        public static string Function_Name_Text {
            get {
                return ResourceManager.GetString("Function_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string K2DVector_X_Text {
            get {
                return ResourceManager.GetString("K2DVector_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string K2DVector_Y_Text {
            get {
                return ResourceManager.GetString("K2DVector_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ambient.
        /// </summary>
        public static string K3DLight_Ambient_Text {
            get {
                return ResourceManager.GetString("K3DLight_Ambient_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attenuation.
        /// </summary>
        public static string K3DLight_Attenuation_Category {
            get {
                return ResourceManager.GetString("K3DLight_Attenuation_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attenuation 1.
        /// </summary>
        public static string K3DLight_Attenuation0_Text {
            get {
                return ResourceManager.GetString("K3DLight_Attenuation0_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attenuation 2.
        /// </summary>
        public static string K3DLight_Attenuation1_Text {
            get {
                return ResourceManager.GetString("K3DLight_Attenuation1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attenuation 3.
        /// </summary>
        public static string K3DLight_Attenuation2_Text {
            get {
                return ResourceManager.GetString("K3DLight_Attenuation2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colors.
        /// </summary>
        public static string K3DLight_Color_Category {
            get {
                return ResourceManager.GetString("K3DLight_Color_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diffuse.
        /// </summary>
        public static string K3DLight_Diffuse_Text {
            get {
                return ResourceManager.GetString("K3DLight_Diffuse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction.
        /// </summary>
        public static string K3DLight_Direction_Text {
            get {
                return ResourceManager.GetString("K3DLight_Direction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fall off.
        /// </summary>
        public static string K3DLight_Falloff_Text {
            get {
                return ResourceManager.GetString("K3DLight_Falloff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phi.
        /// </summary>
        public static string K3DLight_Phi_Text {
            get {
                return ResourceManager.GetString("K3DLight_Phi_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        public static string K3DLight_Position_Text {
            get {
                return ResourceManager.GetString("K3DLight_Position_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Range.
        /// </summary>
        public static string K3DLight_Range_Text {
            get {
                return ResourceManager.GetString("K3DLight_Range_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specular.
        /// </summary>
        public static string K3DLight_Specular_Text {
            get {
                return ResourceManager.GetString("K3DLight_Specular_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theta.
        /// </summary>
        public static string K3DLight_Theta_Text {
            get {
                return ResourceManager.GetString("K3DLight_Theta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string K3DLight_Type_Text {
            get {
                return ResourceManager.GetString("K3DLight_Type_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string K3DVector_X_Text {
            get {
                return ResourceManager.GetString("K3DVector_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string K3DVector_Y_Text {
            get {
                return ResourceManager.GetString("K3DVector_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z.
        /// </summary>
        public static string K3DVector_Z_Text {
            get {
                return ResourceManager.GetString("K3DVector_Z_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alpha.
        /// </summary>
        public static string KColor_A_Text {
            get {
                return ResourceManager.GetString("KColor_A_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue.
        /// </summary>
        public static string KColor_B_Text {
            get {
                return ResourceManager.GetString("KColor_B_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        public static string KColor_Color_Text {
            get {
                return ResourceManager.GetString("KColor_Color_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Green.
        /// </summary>
        public static string KColor_G_Text {
            get {
                return ResourceManager.GetString("KColor_G_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red.
        /// </summary>
        public static string KColor_R_Text {
            get {
                return ResourceManager.GetString("KColor_R_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        public static string KTripleColor_Color_Text {
            get {
                return ResourceManager.GetString("KTripleColor_Color_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lights.
        /// </summary>
        public static string Light_Text {
            get {
                return ResourceManager.GetString("Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bottom.
        /// </summary>
        public static string Location_Bottom_Text {
            get {
                return ResourceManager.GetString("Location_Bottom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        public static string Location_Coordinates_Category {
            get {
                return ResourceManager.GetString("Location_Coordinates_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        public static string Location_Coordinates_Text {
            get {
                return ResourceManager.GetString("Location_Coordinates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Location_Description_Text {
            get {
                return ResourceManager.GetString("Location_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        public static string Location_Left_Text {
            get {
                return ResourceManager.GetString("Location_Left_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Region : {0}.
        /// </summary>
        public static string Location_Name_Text {
            get {
                return ResourceManager.GetString("Location_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        public static string Location_Right_Text {
            get {
                return ResourceManager.GetString("Location_Right_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function.
        /// </summary>
        public static string Location_Script_Text {
            get {
                return ResourceManager.GetString("Location_Script_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locations.
        /// </summary>
        public static string Location_Text {
            get {
                return ResourceManager.GetString("Location_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top.
        /// </summary>
        public static string Location_Top_Text {
            get {
                return ResourceManager.GetString("Location_Top_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string LocationInfo_Collections_Category {
            get {
                return ResourceManager.GetString("LocationInfo_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinate.
        /// </summary>
        public static string LocationInfo_Coordinates_Category {
            get {
                return ResourceManager.GetString("LocationInfo_Coordinates_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string LocationInfo_Description_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Region : {0}.
        /// </summary>
        public static string LocationInfo_Name_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygons.
        /// </summary>
        public static string LocationInfo_Polygons_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Polygons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority.
        /// </summary>
        public static string LocationInfo_Prority_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Prority_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Radius.
        /// </summary>
        public static string LocationInfo_Radius_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Radius_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function.
        /// </summary>
        public static string LocationInfo_Script_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Script_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string LocationInfo_X_Text {
            get {
                return ResourceManager.GetString("LocationInfo_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string LocationInfo_Y_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z.
        /// </summary>
        public static string LocationInfo_Z_Text {
            get {
                return ResourceManager.GetString("LocationInfo_Z_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        public static string MapWorker_Location_Category {
            get {
                return ResourceManager.GetString("MapWorker_Location_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string MapWorker_X_Text {
            get {
                return ResourceManager.GetString("MapWorker_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string MapWorker_Y_Text {
            get {
                return ResourceManager.GetString("MapWorker_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Nfa_Collections_Category {
            get {
                return ResourceManager.GetString("Nfa_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygons.
        /// </summary>
        public static string Nfa_Polygons_Text {
            get {
                return ResourceManager.GetString("Nfa_Polygons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Nfc_Collections_Category {
            get {
                return ResourceManager.GetString("Nfc_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Region.
        /// </summary>
        public static string Nfc_Records_Text {
            get {
                return ResourceManager.GetString("Nfc_Records_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Nfe_Collections_Category {
            get {
                return ResourceManager.GetString("Nfe_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events.
        /// </summary>
        public static string Nfe_Records_Text {
            get {
                return ResourceManager.GetString("Nfe_Records_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Nfl_Collection_Category {
            get {
                return ResourceManager.GetString("Nfl_Collection_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        public static string Nfl_Color_Category {
            get {
                return ResourceManager.GetString("Nfl_Color_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ambiance.
        /// </summary>
        public static string Nfl_DefaultAmbient_Text {
            get {
                return ResourceManager.GetString("Nfl_DefaultAmbient_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diffusion.
        /// </summary>
        public static string Nfl_DefaultDiffuse_Text {
            get {
                return ResourceManager.GetString("Nfl_DefaultDiffuse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        public static string Nfl_DefaultPosition_Text {
            get {
                return ResourceManager.GetString("Nfl_DefaultPosition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specular.
        /// </summary>
        public static string Nfl_DefaultSpecular_Text {
            get {
                return ResourceManager.GetString("Nfl_DefaultSpecular_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lights.
        /// </summary>
        public static string Nfl_Light_Text {
            get {
                return ResourceManager.GetString("Nfl_Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events.
        /// </summary>
        public static string Nfm_DwEventArea_Text {
            get {
                return ResourceManager.GetString("Nfm_DwEventArea_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grass colony.
        /// </summary>
        public static string Nfm_DwGrassColony_Text {
            get {
                return ResourceManager.GetString("Nfm_DwGrassColony_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Props.
        /// </summary>
        public static string Nfm_DwProps_Text {
            get {
                return ResourceManager.GetString("Nfm_DwProps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terrains.
        /// </summary>
        public static string Nfm_DwTerrainSegment_Text {
            get {
                return ResourceManager.GetString("Nfm_DwTerrainSegment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vectors.
        /// </summary>
        public static string Nfm_DwVectorAttr_Text {
            get {
                return ResourceManager.GetString("Nfm_DwVectorAttr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waters.
        /// </summary>
        public static string Nfm_DwWater_Text {
            get {
                return ResourceManager.GetString("Nfm_DwWater_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string Nfm_Information_Category {
            get {
                return ResourceManager.GetString("Nfm_Information_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        public static string Nfm_MapProperties_Text {
            get {
                return ResourceManager.GetString("Nfm_MapProperties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segment per map.
        /// </summary>
        public static string Nfm_SegmentCountPerMap_Text {
            get {
                return ResourceManager.GetString("Nfm_SegmentCountPerMap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        public static string Nfm_Sign_Text {
            get {
                return ResourceManager.GetString("Nfm_Sign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tile per segment.
        /// </summary>
        public static string Nfm_TileCountPerSegment_Text {
            get {
                return ResourceManager.GetString("Nfm_TileCountPerSegment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title len.
        /// </summary>
        public static string Nfm_TileLenght_Text {
            get {
                return ResourceManager.GetString("Nfm_TileLenght_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Nfm_Version_Text {
            get {
                return ResourceManager.GetString("Nfm_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Nfp_Collections_Category {
            get {
                return ResourceManager.GetString("Nfp_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Nfp_Description_Text {
            get {
                return ResourceManager.GetString("Nfp_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id.
        /// </summary>
        public static string Nfp_Id_Text {
            get {
                return ResourceManager.GetString("Nfp_Id_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygons.
        /// </summary>
        public static string Nfp_Polygons_Text {
            get {
                return ResourceManager.GetString("Nfp_Polygons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nfp (Unknow).
        /// </summary>
        public static string Nfp_Text {
            get {
                return ResourceManager.GetString("Nfp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Nfs_Collections_Category {
            get {
                return ResourceManager.GetString("Nfs_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string Nfs_Information_Category {
            get {
                return ResourceManager.GetString("Nfs_Information_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        public static string Nfs_Locations_Text {
            get {
                return ResourceManager.GetString("Nfs_Locations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element Script.
        /// </summary>
        public static string Nfs_Props_Text {
            get {
                return ResourceManager.GetString("Nfs_Props_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Region Scripts.
        /// </summary>
        public static string Nfs_Scripts_Text {
            get {
                return ResourceManager.GetString("Nfs_Scripts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        public static string Nfs_Sign_Text {
            get {
                return ResourceManager.GetString("Nfs_Sign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Nfs_Version_Text {
            get {
                return ResourceManager.GetString("Nfs_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collection.
        /// </summary>
        public static string Nfw_Waters_Category {
            get {
                return ResourceManager.GetString("Nfw_Waters_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waters.
        /// </summary>
        public static string Nfw_Waters_Text {
            get {
                return ResourceManager.GetString("Nfw_Waters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NPC.
        /// </summary>
        public static string NpcProp_Text {
            get {
                return ResourceManager.GetString("NpcProp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Polygon2_Collections_Category {
            get {
                return ResourceManager.GetString("Polygon2_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygons x{0}.
        /// </summary>
        public static string Polygon2_Name_Text {
            get {
                return ResourceManager.GetString("Polygon2_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Points.
        /// </summary>
        public static string Polygon2_Points_Text {
            get {
                return ResourceManager.GetString("Polygon2_Points_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Polygon3_Collections_Category {
            get {
                return ResourceManager.GetString("Polygon3_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygons x{0}.
        /// </summary>
        public static string Polygon3_Name_Text {
            get {
                return ResourceManager.GetString("Polygon3_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Points.
        /// </summary>
        public static string Polygon3_Points_Text {
            get {
                return ResourceManager.GetString("Polygon3_Points_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinate.
        /// </summary>
        public static string Prop_Coordinate_Category {
            get {
                return ResourceManager.GetString("Prop_Coordinate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prop Id.
        /// </summary>
        public static string PROP_DATA_V1_PropIdx_Text {
            get {
                return ResourceManager.GetString("PROP_DATA_V1_PropIdx_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segment Id.
        /// </summary>
        public static string PROP_DATA_V1_SegmentIdx_Text {
            get {
                return ResourceManager.GetString("PROP_DATA_V1_SegmentIdx_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate.
        /// </summary>
        public static string Prop_Field_Category {
            get {
                return ResourceManager.GetString("Prop_Field_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locking.
        /// </summary>
        public static string Prop_Locked_Category {
            get {
                return ResourceManager.GetString("Prop_Locked_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height locked.
        /// </summary>
        public static string Prop_LockedHeight_Text {
            get {
                return ResourceManager.GetString("Prop_LockedHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locking height.
        /// </summary>
        public static string Prop_LockHeight_Text {
            get {
                return ResourceManager.GetString("Prop_LockHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate : {0}.
        /// </summary>
        public static string Prop_Name_Text {
            get {
                return ResourceManager.GetString("Prop_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        public static string Prop_Offset_Category {
            get {
                return ResourceManager.GetString("Prop_Offset_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        public static string Prop_OffSet_Text {
            get {
                return ResourceManager.GetString("Prop_OffSet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        public static string Prop_PropNum_Text {
            get {
                return ResourceManager.GetString("Prop_PropNum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate Id.
        /// </summary>
        public static string Prop_QuestPropID_Text {
            get {
                return ResourceManager.GetString("Prop_QuestPropID_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate.
        /// </summary>
        public static string Prop_Rotate_Category {
            get {
                return ResourceManager.GetString("Prop_Rotate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate X.
        /// </summary>
        public static string Prop_RotateX_Text {
            get {
                return ResourceManager.GetString("Prop_RotateX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate Y.
        /// </summary>
        public static string Prop_RotateY_Text {
            get {
                return ResourceManager.GetString("Prop_RotateY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate Z.
        /// </summary>
        public static string Prop_RotateZ_Text {
            get {
                return ResourceManager.GetString("Prop_RotateZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scale.
        /// </summary>
        public static string Prop_Scale_Category {
            get {
                return ResourceManager.GetString("Prop_Scale_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scale X.
        /// </summary>
        public static string Prop_ScaleX_Text {
            get {
                return ResourceManager.GetString("Prop_ScaleX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scale Y.
        /// </summary>
        public static string Prop_ScaleY_Text {
            get {
                return ResourceManager.GetString("Prop_ScaleY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scale Z.
        /// </summary>
        public static string Prop_ScaleZ_Text {
            get {
                return ResourceManager.GetString("Prop_ScaleZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gates.
        /// </summary>
        public static string Prop_Text {
            get {
                return ResourceManager.GetString("Prop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texture.
        /// </summary>
        public static string Prop_Texture_Category {
            get {
                return ResourceManager.GetString("Prop_Texture_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texture Group.
        /// </summary>
        public static string Prop_TextureGroupIndex_Text {
            get {
                return ResourceManager.GetString("Prop_TextureGroupIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string Prop_X_Text {
            get {
                return ResourceManager.GetString("Prop_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string Prop_Y_Text {
            get {
                return ResourceManager.GetString("Prop_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string PropScriptInfo_Collections_Category {
            get {
                return ResourceManager.GetString("PropScriptInfo_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        public static string PropScriptInfo_Coordinates_Category {
            get {
                return ResourceManager.GetString("PropScriptInfo_Coordinates_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model Id.
        /// </summary>
        public static string PropScriptInfo_ModelId_Text {
            get {
                return ResourceManager.GetString("PropScriptInfo_ModelId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NPC : {0}.
        /// </summary>
        public static string PropScriptInfo_Name_Text {
            get {
                return ResourceManager.GetString("PropScriptInfo_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id.
        /// </summary>
        public static string PropScriptInfo_PropId_Text {
            get {
                return ResourceManager.GetString("PropScriptInfo_PropId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Functions.
        /// </summary>
        public static string PropScriptInfo_Records_Text {
            get {
                return ResourceManager.GetString("PropScriptInfo_Records_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string PropScriptInfo_X_Text {
            get {
                return ResourceManager.GetString("PropScriptInfo_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string PropScriptInfo_Y_Text {
            get {
                return ResourceManager.GetString("PropScriptInfo_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Pvs_Collection_Category {
            get {
                return ResourceManager.GetString("Pvs_Collection_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string Pvs_Information_Category {
            get {
                return ResourceManager.GetString("Pvs_Information_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string Pvs_MapStartPosX_Text {
            get {
                return ResourceManager.GetString("Pvs_MapStartPosX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string Pvs_MapStartPosY_Text {
            get {
                return ResourceManager.GetString("Pvs_MapStartPosY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        public static string Pvs_Position_Category {
            get {
                return ResourceManager.GetString("Pvs_Position_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Props.
        /// </summary>
        public static string Pvs_Prop_Text {
            get {
                return ResourceManager.GetString("Pvs_Prop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string PVS_PROP_V1_Collection_Category {
            get {
                return ResourceManager.GetString("PVS_PROP_V1_Collection_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additional Props.
        /// </summary>
        public static string PVS_PROP_V1_IncludeProps_Text {
            get {
                return ResourceManager.GetString("PVS_PROP_V1_IncludeProps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string PVS_PROP_V1_SegmentX_Text {
            get {
                return ResourceManager.GetString("PVS_PROP_V1_SegmentX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string PVS_PROP_V1_SegmentY_Text {
            get {
                return ResourceManager.GetString("PVS_PROP_V1_SegmentY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Props.
        /// </summary>
        public static string Pvs_Props_Text {
            get {
                return ResourceManager.GetString("Pvs_Props_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segment position.
        /// </summary>
        public static string Pvs_Segment_Category {
            get {
                return ResourceManager.GetString("Pvs_Segment_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string PVS_SEGMENT_V1_Collection_Category {
            get {
                return ResourceManager.GetString("PVS_SEGMENT_V1_Collection_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additional Segments.
        /// </summary>
        public static string PVS_SEGMENT_V1_IncludeSegments_Text {
            get {
                return ResourceManager.GetString("PVS_SEGMENT_V1_IncludeSegments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string PVS_SEGMENT_V1_SegmentX_Text {
            get {
                return ResourceManager.GetString("PVS_SEGMENT_V1_SegmentX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string PVS_SEGMENT_V1_SegmentY_Text {
            get {
                return ResourceManager.GetString("PVS_SEGMENT_V1_SegmentY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bottom.
        /// </summary>
        public static string Pvs_SegmentBottom_Text {
            get {
                return ResourceManager.GetString("Pvs_SegmentBottom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of segment.
        /// </summary>
        public static string Pvs_SegmentCountPerMap_Text {
            get {
                return ResourceManager.GetString("Pvs_SegmentCountPerMap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        public static string Pvs_SegmentLeft_Text {
            get {
                return ResourceManager.GetString("Pvs_SegmentLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        public static string Pvs_SegmentRight_Text {
            get {
                return ResourceManager.GetString("Pvs_SegmentRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segments.
        /// </summary>
        public static string Pvs_Segments_Text {
            get {
                return ResourceManager.GetString("Pvs_Segments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top.
        /// </summary>
        public static string Pvs_SegmentTop_Text {
            get {
                return ResourceManager.GetString("Pvs_SegmentTop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        public static string Pvs_Sign_Text {
            get {
                return ResourceManager.GetString("Pvs_Sign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Pvs_Version_Text {
            get {
                return ResourceManager.GetString("Pvs_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occlusion prop.
        /// </summary>
        public static string PVSProp_Text {
            get {
                return ResourceManager.GetString("PVSProp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occlusion segment.
        /// </summary>
        public static string PVSSegment_Text {
            get {
                return ResourceManager.GetString("PVSSegment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Qpf_Collections_Category {
            get {
                return ResourceManager.GetString("Qpf_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string Qpf_Information_Category {
            get {
                return ResourceManager.GetString("Qpf_Information_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate.
        /// </summary>
        public static string Qpf_Prop_Text {
            get {
                return ResourceManager.GetString("Qpf_Prop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        public static string Qpf_Sign_Text {
            get {
                return ResourceManager.GetString("Qpf_Sign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Qpf_Version_Text {
            get {
                return ResourceManager.GetString("Qpf_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regions.
        /// </summary>
        public static string Region_Text {
            get {
                return ResourceManager.GetString("Region_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string Script_Collections_Category {
            get {
                return ResourceManager.GetString("Script_Collections_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script region : {0}.
        /// </summary>
        public static string Script_Name_Text {
            get {
                return ResourceManager.GetString("Script_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Functions.
        /// </summary>
        public static string Script_Records_Text {
            get {
                return ResourceManager.GetString("Script_Records_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Région Id.
        /// </summary>
        public static string Script_RegionIndex_Text {
            get {
                return ResourceManager.GetString("Script_RegionIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string SEGMENT_DATA_V1_SegmentX_Text {
            get {
                return ResourceManager.GetString("SEGMENT_DATA_V1_SegmentX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string SEGMENT_DATA_V1_SegmentY_Text {
            get {
                return ResourceManager.GetString("SEGMENT_DATA_V1_SegmentY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ambiance.
        /// </summary>
        public static string StructLights_Ambient_Text {
            get {
                return ResourceManager.GetString("StructLights_Ambient_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        public static string StructLights_Color_Category {
            get {
                return ResourceManager.GetString("StructLights_Color_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diffusion.
        /// </summary>
        public static string StructLights_Diffuse_Text {
            get {
                return ResourceManager.GetString("StructLights_Diffuse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction.
        /// </summary>
        public static string StructLights_Direction_Text {
            get {
                return ResourceManager.GetString("StructLights_Direction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intensity.
        /// </summary>
        public static string StructLights_Height_Text {
            get {
                return ResourceManager.GetString("StructLights_Height_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of light.
        /// </summary>
        public static string StructLights_LightType_Text {
            get {
                return ResourceManager.GetString("StructLights_LightType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string StructLights_Name_Text {
            get {
                return ResourceManager.GetString("StructLights_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        public static string StructLights_Position_Text {
            get {
                return ResourceManager.GetString("StructLights_Position_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specular.
        /// </summary>
        public static string StructLights_Specular_Text {
            get {
                return ResourceManager.GetString("StructLights_Specular_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lights.
        /// </summary>
        public static string StructLights_Text {
            get {
                return ResourceManager.GetString("StructLights_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collisions.
        /// </summary>
        public static string Template_Collision_Text {
            get {
                return ResourceManager.GetString("Template_Collision_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colored.
        /// </summary>
        public static string Template_Color_Category {
            get {
                return ResourceManager.GetString("Template_Color_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events.
        /// </summary>
        public static string Template_EventArea_Text {
            get {
                return ResourceManager.GetString("Template_EventArea_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string Template_Light_Text {
            get {
                return ResourceManager.GetString("Template_Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locations.
        /// </summary>
        public static string Template_Location_Text {
            get {
                return ResourceManager.GetString("Template_Location_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nfp (Unknow).
        /// </summary>
        public static string Template_Nfp_Text {
            get {
                return ResourceManager.GetString("Template_Nfp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NPC.
        /// </summary>
        public static string Template_NpcProp_Text {
            get {
                return ResourceManager.GetString("Template_NpcProp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gates.
        /// </summary>
        public static string Template_Prop_Text {
            get {
                return ResourceManager.GetString("Template_Prop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occlusion prop.
        /// </summary>
        public static string Template_PVSProp_Text {
            get {
                return ResourceManager.GetString("Template_PVSProp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occlusion segment.
        /// </summary>
        public static string Template_PVSSegment_Text {
            get {
                return ResourceManager.GetString("Template_PVSSegment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regions.
        /// </summary>
        public static string Template_Region_Text {
            get {
                return ResourceManager.GetString("Template_Region_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waters.
        /// </summary>
        public static string Template_Water_Text {
            get {
                return ResourceManager.GetString("Template_Water_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        public static string Water_Coordinates_Category {
            get {
                return ResourceManager.GetString("Water_Coordinates_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water : {0}.
        /// </summary>
        public static string Water_Name_Text {
            get {
                return ResourceManager.GetString("Water_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Angle 1.
        /// </summary>
        public static string Water_Point01_Text {
            get {
                return ResourceManager.GetString("Water_Point01_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Angle 2.
        /// </summary>
        public static string Water_Point02_Text {
            get {
                return ResourceManager.GetString("Water_Point02_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center.
        /// </summary>
        public static string Water_Point03_Text {
            get {
                return ResourceManager.GetString("Water_Point03_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waters.
        /// </summary>
        public static string Water_Text {
            get {
                return ResourceManager.GetString("Water_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use reflection.
        /// </summary>
        public static string Water_UseReflect_Text {
            get {
                return ResourceManager.GetString("Water_UseReflect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water Id.
        /// </summary>
        public static string Water_WaterId_Text {
            get {
                return ResourceManager.GetString("Water_WaterId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string Water_X_Text {
            get {
                return ResourceManager.GetString("Water_X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string Water_Y_Text {
            get {
                return ResourceManager.GetString("Water_Y_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z.
        /// </summary>
        public static string Water_Z_Text {
            get {
                return ResourceManager.GetString("Water_Z_Text", resourceCulture);
            }
        }
    }
}
